include: package:pedantic/analysis_options.yaml

linter:
  rules:

# Style rules

    - camel_case_types
    - library_names
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_empty_else
    - empty_statements
    - unnecessary_parenthesis
    - unnecessary_this
    - unnecessary_const
    - unnecessary_overrides
    - unnecessary_lambdas
    - unnecessary_brace_in_string_interps
    - prefer_const_literals_to_create_immutables
# formatting
    - lines_longer_than_80_chars
    - curly_braces_in_flow_control_structures

# doc comments
    - slash_for_doc_comments
    - avoid_print

analyzer:
  errors:
    omit_local_variable_types: ignore
    lines_longer_than_80_chars: ignore
